### ISSUE TITLE
Testing it.. fail again xD

### ISSUE THREAD

**Issue by HasanY1989** [Fiaxhs/pgmap#12]
I chnaged the config, did everything i di as last time. 

and it gave me this error 

> C:\Users\Haso\Desktop\Poke Server test1\pgmap-master\node_modules\iterator-tools\dist\index.js:153
>   constructor(iterable, fn=add) {
>                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Haso\Desktop\Poke Server test1\pgmap-master\src\app.js:7:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by Fiaxhs** [comment]
Hi @HasanY1989, you need to update node to latest version.
Then remove the folder called `node_modules` in the `pgmap` folder and run `npm install` again.

**Comment by HasanY1989** [comment]
Okay will try this later ty
