### ISSUE TITLE
run start error

### ISSUE THREAD

**Issue by vinsilsim** [Fiaxhs/pgmap#15]
anyone know how to solve?

> pgmap@0.0.1 start /root/pgmap
> node src/app.js

/root/pgmap/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (/root/pgmap/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/root/pgmap/node_modules/s2geometry-node/index.js:1:104)
    at Module._compile (module.js:541:32)

**Comment by BenoitZugmeyer** [comment]
It looks like you updated your nodejs version after installing pgmap.
Try:

```
cd /root/pgmap
rm -rf node_modules
npm install
npm start
```

**Comment by vinsilsim** [comment]
@BenoitZugmeyer work! thank you!
