### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by HasanY1989** [Fiaxhs/pgmap#19]
Downloaded new zip to test it out. 
but i get this error after i chnage config
and did npm install 

then i did npm run even tried with npm run start 

This error commes:
\Desktop\pgmap-master\node_modules\iterator-tools\dist\index.js:153
  constructor(iterable, fn=add) {
                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Haso\Desktop\pgmap-master\src\app.js:7:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

I did npm update but still didnt help

**Comment by Fiaxhs** [comment]
Please install the latest version of nodejs, should correct your issue. (then delete node_modules folders, then run `npm install` and `npm run start` )
