### ISSUE TITLE
Start Map Error

### ISSUE THREAD

**Issue by vinsilsim** [Fiaxhs/pgmap#23]
[root@CentOS-72-64-minimal pgmap]# npm run start

> pgmap@0.0.1 start /root/pgmap
> node src/app.js

/root/pgmap/src/app.js:3
const express = require('express'),
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! weird error 8
npm ERR! not ok code 0

**Comment by BenoitZugmeyer** [comment]
Please use a newer version of nodejs (6+)
