### ISSUE TITLE
heartbeat error!

### ISSUE THREAD

**Issue by vinsilsim** [Fiaxhs/pgmap#27]
Error while crawling location: Error: Unexpected heartbeat response
    at /root/pgmap/src/crawl.js:29:31
    at /root/pgmap/node_modules/pokemon-go-node-api/poke.io.js:409:7
    at Request._callback (/root/pgmap/node_modules/pokemon-go-node-api/poke.io.js:230:18)
    at Request.self.callback (/root/pgmap/node_modules/pokemon-go-node-api/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/pgmap/node_modules/pokemon-go-node-api/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/pgmap/node_modules/pokemon-go-node-api/node_modules/request/request.js:965:12)

**Comment by HasanY1989** [comment]
Just delete the whole file, download it again, get the newst node.js then npm install, and npm run start

**Comment by vinsilsim** [comment]
@HasanY1989 i do. but same error!

**Comment by HasanY1989** [comment]
what vision is your node.js?

**Comment by vinsilsim** [comment]
@HasanY1989 
[root@200-98-129-194 pgmap2]# node -v
v6.4.0

**Comment by HasanY1989** [comment]
Do you have micrsoft compile python ?
and micrsoft viseult 2015

try do write this ind cmd "npm -g install npm@next" and then install npm and run it

**Comment by Fiaxhs** [comment]
@vinsilsim I think your pokemon GO account might be banned. Try with another one.
